### ISSUE TITLE
Custom Pool

### ISSUE THREAD

**Issue by DarrenRainey** [CollusionPool/Collusion#1]
can you add an option to chose a different pool ?

**Comment by CollusionPool** [comment]
Temporarily not, because we need to develop our pool, but in a short time I will make it affordable for all pools.

Thank you for understanding

**Comment by DarrenRainey** [comment]
OK just tried out the pool eailer as well

**Comment by CollusionPool** [comment]
You can try our pool, we have you can see all the detailed statistics
